config/routes.rb
Rails.application.routes.draw do

  get 'entries/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :entries

  root 'entries#index'
  get 'entries/new' => 'entries#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  validates :description, presence: true
  validates :date,presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  def index
    @entries = Entry.order(date: :desc)
  end

  def show
    @entry = Entry.find(params[:id])
  end

  def new
    @entry = Entry.new
  end

  def edit
    @entry = Entry.find(params[:id])
  end

  def create
    # render plain: params[:entry].inspect
    @entry = Entry.new(entry_params)

    if @entry.save
      redirect_to @entry
    else
      render 'new'
    end
  end

  def update
    @entry = Entry.find(params[:id])

    if @entry.update(entry_params)
      redirect_to @entry
    else
      render 'edit'
    end
  end

  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    redirect_to entries_path
  end

  private
    def entry_params
      params.require(:entry).permit(:date, :description)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/entries/_form.html.erb
<%= form_with(model: @entry, local: true) do |form| %>
<% if @entry.errors.any? %>
  <div id="error_explanation">
    <h2>Entry can't save...!</h2>
    <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="form-group">
  <p>
    <%= form.label :date %><br>
    <%= form.text_field :date %>
  </p>
</div>
<div class="form-group">
  <p>
   <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>
</div>
<div class="form-group">
  <p>
    <%= form.submit %>
  </p>
</div>
<% end %>

app/views/entries/edit.html.erb
<div class="container">
    <h1>Edit Entry</h1>
    <%= render 'form' %>
</div>

<div class="card bg-secondary text-white">
  <div class="card-body" align="center">
    <%= button_to "Back", entries_path, :method => "get" %>
  </div>
</div>

app/views/entries/index.html.erb
<h1 class="jumbotron text-center">Listing Entries</h1>
</div class="container">
  <div class="card bg-secondary text-white">
    <div class="card-body" align="center">
      <%= button_to "ADD ENTRY", new_entry_path, :method => "get" %>
    </div>
  </div>
</div>
<div class="container">
  <table class="table">
    <tr>
      <th>Date</th>
      <th>Description</th>
      <th></th>
    </tr>

    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.date %></td>
        <td><%= entry.description %></td>
        <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
        <td><%= link_to 'Show', entry_path(entry) %></td>
        <td><%= link_to 'Delete', entry_path(entry), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/entries/new.html.erb
<%= form_with scope: :entry, url: entries_path, local: true do |form| %>
  <p>
    <%= form.label :date %><br>
    <%= form.text_field :date %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/entries/show.html.erb
<div class="container" align="center">
  <div class="card bg-secondary text-white">
    <div class="card-body">
      <p>
        <strong class="font-weight-bolder">Date:</strong>
        <%= @entry.date %>
      </p>
    </div>
  </div

  <div class="card">
    <div class="card-body">
      <p>
        <strong class="font-weight-bolder" font-size="60">Description:</strong>
        <%= @entry.description %>
      </p>
    </div>
  </div>

</div>
<div class="card bg-secondary text-white">
  <div class="card-body" align="center">
    <%= button_to "Back", entries_path, :method => "get" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DiaryApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails</h1>